services:
  app:
    image: sibackend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME=VBsoftwareeng
      # - MONGODB_PASSWORD=ozX5YTe3eLwR0wXS
      # - MONGODB_DATABASE
      # - MONGODB_REMOTE =1
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/cicd201
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongodb:
    image: mongo
    ports:
      - 27017:27017
